### PR TITLE
Stick to specific version of Buzz to avoid conflicts

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by ruudk** [comment]
@miguel250 Could you merge this and create a new tag? Thanks!

**Comment by miguel250** [comment]
Hey @ruudk the reason i am using the master branch is because the bundle needs this commit to work correctly. https://github.com/kriswallsmith/Buzz/commit/1ce0f4bc574e3da3e11744ea0125ec76ae72bf8d

You can see that the tests failed because of it. https://travis-ci.org/#!/miguel250/PostmarkBundle/builds/2734776

**Comment by miguel250** [comment]
@ruudk  can you update this pull request to use v0.9 of buzz?

**Comment by ruudk** [comment]
Done!

**Comment by miguel250** [comment]
Thx!!

**Comment by ruudk** [comment]
Thanks, please create a tag for your own bundle :)

**Comment by miguel250** [comment]
Done.

**Pull request merged**
